language: python
env:
    - COVERAGE=--with-coverage
python:
    - "2.7"
    - "2.6"
virtualenv:
    system_site_packages: true
before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then wget -O- http://neuro.debian.net/lists/precise.us-nh.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9; fi
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose
    - sudo apt-get install python-pip
install:
    - python setup.py build_ext --inplace
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coverage; fi
    - if [ "${COVERAGE}" == "--with-coverage" ]; then sudo pip install coveralls; fi
script:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then
    -   make test-coverage;
    - else
    -   make test;
    - fi
after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi

