language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"
      COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="2.6" INSTALL_MKL="false"
      NUMPY_VERSION="1.6.2" SCIPY_VERSION="0.11.0"
    - DISTRIB="conda" PYTHON_VERSION="3.3" INSTALL_MKL="true"
      NUMPY_VERSION="1.8.1" SCIPY_VERSION="0.13.3"
install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls; fi
cache: apt
